"""add_processed_episodes_table

Revision ID: 634e2df60ec1
Revises: 8e4768e52334
Create Date: 2025-06-26 20:04:05.420068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '634e2df60ec1'
down_revision = '8e4768e52334'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.String(), nullable=False),
    sa.Column('episode_title', sa.String(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.Column('books_found', sa.Integer(), nullable=False),
    sa.Column('parsing_method', sa.String(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_episodes_episode_id'), 'processed_episodes', ['episode_id'], unique=True)
    op.create_index(op.f('ix_processed_episodes_id'), 'processed_episodes', ['id'], unique=False)
    op.alter_column('books', 'episode_title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('books', 'rating_distribution')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('rating_distribution', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.alter_column('books', 'episode_title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_processed_episodes_id'), table_name='processed_episodes')
    op.drop_index(op.f('ix_processed_episodes_episode_id'), table_name='processed_episodes')
    op.drop_table('processed_episodes')
    # ### end Alembic commands ### 