"""add_goodreads_fields

Revision ID: 8e4768e52334
Revises: 
Create Date: 2025-06-12 00:29:43.092085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e4768e52334'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('books', sa.Column('rating_distribution', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('books', sa.Column('goodreads_url', sa.String(), nullable=True))
    op.add_column('books', sa.Column('publication_date', sa.DateTime(), nullable=True))
    op.add_column('books', sa.Column('num_pages', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('format', sa.String(), nullable=True))
    op.add_column('books', sa.Column('isbn', sa.String(), nullable=True))
    op.add_column('books', sa.Column('language', sa.String(), nullable=True))
    op.add_column('books', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('books', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_books_genre', table_name='books')
    op.create_index(op.f('ix_books_genres'), 'books', ['genres'], unique=False)
    op.create_unique_constraint(None, 'books', ['goodreads_url'])
    op.drop_column('books', 'genre')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_index(op.f('ix_books_genres'), table_name='books')
    op.create_index('ix_books_genre', 'books', ['genre'], unique=False)
    op.drop_column('books', 'updated_at')
    op.drop_column('books', 'created_at')
    op.drop_column('books', 'language')
    op.drop_column('books', 'isbn')
    op.drop_column('books', 'format')
    op.drop_column('books', 'num_pages')
    op.drop_column('books', 'publication_date')
    op.drop_column('books', 'goodreads_url')
    op.drop_column('books', 'rating_distribution')
    op.drop_column('books', 'genres')
    # ### end Alembic commands ### 